# Load & Prep Data

In [1]:
from sklearn.datasets import load_boston
import pandas as pd 
import numpy as np

boston = load_boston()



In [2]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [3]:
boston.data[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [4]:
boston.target[0]

24.0

In [5]:
X = boston.data
y = boston.target

In [6]:
X.shape

(506, 13)

In [7]:
df = pd.DataFrame(X)
df.describe()

0           1           2           3           4           5   \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

               6           7           8           9           10          11  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

               12  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [8]:
df = pd.concat((df,pd.DataFrame(y,columns=['y'])),axis=1)
df.columns=['0','1','2','3','4','5','6','7','8','9','10','11','12','y']
df.head()

0     1     2    3      4      5     6       7    8      9    10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12     y  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [9]:
x1 = df['0']
x2 = df['1']
x3 = df['2']
x4 = df['3']
x5 = df['4']
x6 = df['5']
x7 = df['6']
x8 = df['7']
x9 = df['8']
x10 = df['9']
x11 = df['10']
x12 = df['11']
x13 = df['12']
y = df['y']

In [10]:
df['diff']=np.NaN
df['yhat']=np.NaN

In [11]:
thetas=[38.091694926302125,
 -0.11944344700245635,
 0.044779951066510684,
 0.005485261681774737,
 2.3408036062420767,
 -16.1236043154296,
 3.708709012219163,
 -0.0031210817807345867,
 -1.3863973702786825,
 0.24417832698880473,
 -0.010989636563079976,
 -1.0459211887459754,
 0.008110106932705016,
 -0.4927927245047084]

In [12]:
len(thetas)

14

In [13]:
for step in range(3):
    t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13=(thetas[0],thetas[1],thetas[2],thetas[3],thetas[4],thetas[5],thetas[6],thetas[7],
                                                   thetas[8],thetas[9],thetas[10],thetas[11],thetas[12],thetas[13])
    df['yhat']=t0+t1*x1+t2*x2+t3*x3+t4*x4+t5*x5+t6*x6+t7*x7+t8*x8+t9*x9+t10*x10+t11*x11+t12*x12+t13*x13
    df['diff']=(df.y-df.yhat)**2
    cost = (df['diff'].sum())/(2*df['diff'].shape[0])
    print('\n\n')
    print('For step : ', step)
    print('Cost is : ', cost)
    step_size = 0.01
    
    for i in range(len(thetas)):
        thetas[i]=thetas[i] - (step_size/df['diff'].shape[0])*(np.sqrt(df['diff']).sum())
    print('Gradient Decent optimized thetas : ', thetas)
    
    




For step :  0
Cost is :  11.086650120564858
Gradient Decent optimized thetas :  [38.05917216099178, -0.15196621231280077, 0.012257185756166265, -0.02703750362856968, 2.308280840931732, -16.156127080739942, 3.6761862469088182, -0.035643847091079005, -1.4189201355890269, 0.2116555616784603, -0.043512401873424394, -1.0784439540563198, -0.024412658377639403, -0.5253154898150528]



For step :  1
Cost is :  470.9088278669744
Gradient Decent optimized thetas :  [37.76205250495236, -0.4490858683522218, -0.2848624702832548, -0.3241571596679907, 2.011161184892311, -16.453246736779363, 3.3790665908693973, -0.3327635031305, -1.716039791628448, -0.08546409436096072, -0.34063205791284545, -1.3755636100957407, -0.3215323144170604, -0.8224351458544739]



For step :  2
Cost is :  46936.25791977324
Gradient Decent optimized thetas :  [34.75531576421969, -3.455822609084891, -3.291599211015924, -3.33089390040066, -0.9955755558403578, -19.459983477512033, 0.37232985013672826, -3.339500243863169, -4.72

# Making Regression model

In [14]:
# Sperate train and test data
X = boston.data
y = boston.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [15]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

model.score(X_test, y_test)

0.5892223849182514

# Extracting coef values

In [16]:
model.coef_

array([-1.19443447e-01,  4.47799511e-02,  5.48526168e-03,  2.34080361e+00,
       -1.61236043e+01,  3.70870901e+00, -3.12108178e-03, -1.38639737e+00,
        2.44178327e-01, -1.09896366e-02, -1.04592119e+00,  8.11010693e-03,
       -4.92792725e-01])

In [17]:
model.intercept_

38.091694926302125

In [18]:
thetas = [model.intercept_]
thetas.extend(model.coef_) 
thetas

[38.091694926302125,
 -0.11944344700245635,
 0.044779951066510684,
 0.005485261681774737,
 2.3408036062420767,
 -16.1236043154296,
 3.708709012219163,
 -0.0031210817807345867,
 -1.3863973702786825,
 0.24417832698880473,
 -0.010989636563079976,
 -1.0459211887459754,
 0.008110106932705016,
 -0.4927927245047084]

# Gradient Decent

In [19]:
yhat = model.predict(X_test)
yhat

array([24.88963777, 23.72141085, 29.36499868, 12.12238621, 21.44382254,
       19.2834443 , 20.49647539, 21.36099298, 18.8967118 , 19.9280658 ,
        5.12703513, 16.3867396 , 17.07776485,  5.59375659, 39.99636726,
       32.49654668, 22.45798809, 36.85192327, 30.86401089, 23.15140009,
       24.77495789, 24.67187756, 20.59543752, 30.35369168, 22.41940736,
       10.23266565, 17.64816865, 18.27419652, 35.53362541, 20.96084724,
       18.30413012, 17.79262072, 19.96561663, 24.06127231, 29.10204874,
       19.27774123, 11.15536648, 24.57560579, 17.5862644 , 15.49454112,
       26.20577527, 20.86304693, 22.31460516, 15.60710156, 23.00363104,
       25.17247952, 20.11459464, 22.90256276, 10.0380507 , 24.28515123,
       20.94127711, 17.35258791, 24.52235405, 29.95143046, 13.42695877,
       21.72673066, 20.7897053 , 15.49668805, 13.98982601, 22.18377874,
       17.73047814, 21.58869165, 32.90522136, 31.11235671, 17.73252635,
       32.76358681, 18.7124637 , 19.78693475, 19.02958927, 22.89

In [20]:
df = pd.DataFrame([y_test,yhat]).transpose()
df.columns = ['y','yhat']
df.head()

y       yhat
0  22.6  24.889638
1  50.0  23.721411
2  23.0  29.364999
3   8.3  12.122386
4  21.2  21.443823

In [21]:
df['diff'] = (df.y-df.yhat)**2
df.head()

y       yhat        diff
0  22.6  24.889638    5.242441
1  50.0  23.721411  690.564248
2  23.0  29.364999   40.513208
3   8.3  12.122386   14.610636
4  21.2  21.443823    0.059449

In [22]:
cost = (df['diff'].sum())/(2*df['diff'].shape[0])
cost

16.724489998838237

In [23]:
step_size = 0.01
j = 0
for i in range(len(thetas)):
    thetas[i]=thetas[i] - (step_size/df['diff'].shape[0])*(np.sqrt(df['diff']).sum())
    print(thetas[i])


38.05326583409768
-0.1578725392069013
0.006350858862065718
-0.03294383052267023
2.302374514037632
-16.162033407634045
3.670279920014718
-0.04155017398517955
-1.4248264624831275
0.20574923478435977
-0.04941872876752494
-1.0843502809504204
-0.03031898527173995
-0.5312218167091534
